# Generated by Django 4.0.3 on 2022-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
