# Generated by Django 4.0.3 on 2022-04-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0002_alter_driver_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', location_field.models.plain.PlainLocationField(max_length=63)),
                ('end', location_field.models.plain.PlainLocationField(max_length=63)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('trip_time', models.TimeField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='taxi.driver')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
