# Generated by Django 3.2.12 on 2022-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_rename_end_order_drop_off_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
    ]
