# Generated by Django 3.2 on 2022-04-12 12:06

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_remove_driver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In_progress'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_history', to='taxi.driver')),
            ],
        ),
    ]
