# Generated by Django 3.2 on 2022-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20220412_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='driver',
            name='last_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
