# Generated by Django 3.2 on 2022-04-12 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20220412_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_lat',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_long',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='long',
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_off_address',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_address',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
