# Generated by Django 3.2 on 2022-04-12 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_auto_20220412_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
