# Generated by Django 3.2 on 2022-04-14 12:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0011_alter_driver_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
