# Generated by Django 3.2 on 2022-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0014_auto_20220416_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
