# Generated by Django 3.2 on 2022-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0016_ordernotificationdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
