# Generated by Django 3.2 on 2022-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0019_alter_order_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
