# Generated by Django 3.2 on 2022-04-22 09:31

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('is_hurted', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=support.models.get_file_path_post)),
            ],
        ),
    ]
